### ISSUE TITLE
Use Sqlite by default?

### ISSUE THREAD

**Issue by ciromine** [jameschambers/boring-bits-rails-api#3]
Is possible to use SQLITE by default? I tested in my local PC and I don't have PGSQL and the template shows me an error:

```
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Couldn't create 'PetAppApi_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

**Comment by jameschambers** [comment]
Hi there, yes you should be able to swap out `pg` for `sqlite` in the Gemfile, then run bundle install. There's nothing postgres-specific about the setup so any database adapter should work.

**Comment by ciromine** [comment]
This is strange I run the command:

`rails new PetAppApi --api -m ../Proyectos/boring-bits-rails-api/template.rb`

But I ge the error:

```
generate    migration
       rails    generate migration CreateJwtDenylist jti:string:index expired_at:datetime
      invoke  active_record
      create    db/migrate/20210707230507_create_jwt_denylist.rb
       rails    db:create
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Couldn't create 'PetAppApi_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```
and if I check the database.yml I got this:

```
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PetAppApi_development

test:
  <<: *default
  database: PetAppApi_test

production:
  <<: *default
  database: PetAppApi_production
```
 I don't know why always generate with pg conection. Also if I change the database.yml and run 

rake db:create

I got:

```
rake db:create
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
```
